import Navbar from "@/Components/Navbar";
import "./globals.css";
import { Roboto } from 'next/font/google'

const interFont = Roboto({ weight : "400", preload : false})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={interFont.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
